### ISSUE TITLE
Use Dependabot to automatically check for lockfile updates

### ISSUE THREAD

**Issue by mitchmindtree** [essential-contributions/essential-server#125]
I got an LLM to generate this short guide on how to set it up - probs wanna double check this for hallucinations:

---

Sure! Here's a short guide on how to use Dependabot to automatically update `Cargo.lock` files in a Rust project repository and open pull requests for these updates.

#### 1. Create the `dependabot.yml` Configuration File
First, you need to create a configuration file for Dependabot. This file should be placed in the `.github` directory of your repository.

```yaml
# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
```

#### 2. Configuration Options
- **version**: Specifies the version of the Dependabot configuration file format. The current version is 2.
- **updates**: A list of update configurations.
  - **package-ecosystem**: Specifies the package manager to use. For Rust, this should be set to `"cargo"`.
  - **directory**: The directory where the `Cargo.toml` file is located. For most projects, this is the root directory (`"/"`).
  - **schedule**: Defines how often to check for updates. Possible values include `daily`, `weekly`, and `monthly`.

#### 3. Customize Your Configuration (Optional)
You can customize the Dependabot configuration to suit your needs. Here are some additional options you might find useful:

- **open-pull-requests-limit**: Limits the number of open pull requests. This can help avoid overwhelming your project with too many updates at once.

```yaml
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
```

- **ignore**: Ignore specific dependencies if you don't want Dependabot to update them.

```yaml
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "some-dependency"
        versions: ["1.x"]
```

#### 4. Enable and Configure Dependabot Alerts
Ensure that Dependabot alerts are enabled for your repository to get notifications about vulnerabilities and updates.

1. Go to the repository on GitHub.
2. Click on the `Settings` tab.
3. Under `Security & analysis`, enable `Dependabot alerts` and `Dependabot security updates`.

#### 5. Commit and Push the Configuration
After setting up the `dependabot.yml` file, commit and push it to your repository.

```bash
git add .github/dependabot.yml
git commit -m "Add Dependabot configuration for Cargo updates"
git push origin main
```

#### 6. Review and Merge Pull Requests
Dependabot will now automatically check for updates according to the schedule you've set. It will open pull requests for updates to your `Cargo.lock` file, which you can review and merge.

### Example of a Pull Request Created by Dependabot

When Dependabot finds updates, it will create a pull request similar to this:

```
Bump some-dependency from 1.2.3 to 1.2.4

Bumps [some-dependency](https://github.com/dependency/repo) from 1.2.3 to 1.2.4.
- [Release notes](https://github.com/dependency/repo/releases)
- [Changelog](https://github.com/dependency/repo/blob/main/CHANGELOG.md)
- [Commits](https://github.com/dependency/repo/compare/v1.2.3...v1.2.4)
```

Review the changes and merge the pull request to update your dependencies.

### Additional Resources
- [Dependabot Version Updates Documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-dependency-updates)
- [GitHub Dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/)

By following these steps, you can ensure that your Rust project dependencies are kept up-to-date automatically with Dependabot.
