### ISSUE TITLE
Get Nix working in CI with private SSH access

### ISSUE THREAD

**Issue by mitchmindtree** [essential-contributions/essential-server#49]
Previously attempted to add the following with #46, but appears to need some more attention and as it's not high priority I'm opening an issue to dig into this another time.

```yaml
  nix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - command: fmt -- --check ./
          - command: flake check --all-systems
    steps:
    - name: Provide Access to Private Repos
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
            ${{ secrets.SSH_PRIVATE_KEY_SELF }}
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@main
    - run: nix ${{ matrix.command }}
```
